name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "a89f8e90-443d-4212-bf94-83fb24a9e6f4"      # 替换为你创建的数据库 ID
