name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "newsnow_db"
database_name = "newsnow-db"
database_id = "a89f8e90-443d-4212-bf94-83fb24a9e6f4"
